name: Rust Compiler Builder

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/README.md'
  schedule:
    # https://crontab.guru/
    # At 12:00 AM, only on Monday
    - cron: 0 0 * * 1

jobs:
  build:
    name: ${{ matrix.rust-targets }} [${{ matrix.xcode-version }}] [${{ matrix.os }}]
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://github.com/actions/runner-images?tab=readme-ov-file#available-images
          # https://github.com/actions/runner-images/tree/main/images/macos
          # https://developer.apple.com/support/xcode/

          # Regression: arm64e-apple-darwin
          # Regression: arm64e-apple-ios
          # Regression: aarch64-apple-tvos
          # Regression: macos-14 arm64

          - rust-targets: aarch64-apple-darwin
            os: macos-13 # x86-64
            xcode-version: 14.3.1
            rust-config: configure
            rust-verbose-level: 3
            rust-use-lld: true
            macosx_deployment_target: 11.0
            iphoneos_deployment_target: 14.0

          - rust-targets: aarch64-apple-ios
            os: macos-13 # x86-64
            xcode-version: 14.3.1
            rust-config: configure
            rust-verbose-level: 3
            rust-use-lld: true
            macosx_deployment_target: 11.0
            iphoneos_deployment_target: 14.0

    runs-on: ${{ matrix.os }}
    env:
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.macosx_deployment_target }}
      IPHONEOS_DEPLOYMENT_TARGET: ${{ matrix.iphoneos_deployment_target }}
      RUST_TARGETS: ${{ matrix.rust-targets }}

    steps:
      - name: Install Xcode ${{ matrix.xcode-version }}
        run: |
          sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app
          sudo xcode-select -p

      - name: Install Ninja
        run: brew install ninja

      - name: Install sccache
        run: brew install sccache

      - name: Install llvm
        run: |
          brew install llvm
          echo "PATH=$PATH:/opt/homebrew/opt/llvm/bin:/usr/local/opt/llvm/bin" >> $GITHUB_ENV

      - name: Show System Info
        run: |
          echo $PATH
          uname -a
          xcodebuild -version
          xcrun --show-sdk-path
          sccache --version
          cmake --version
          ninja --version
          clang -v
          ld -v
          lld -flavor ld --version
          df -h .

      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Rust
        uses: actions/checkout@v4
        with:
          repository: rust-lang/rust
          ref: master
          submodules: true
          path: rust

      - name: Configure Rust
        run: make ${{ matrix.rust-config }}
        env:
          RUST_VERBOSE: ${{ matrix.rust-verbose-level }}
          RUST_USE_LLD: ${{ matrix.rust-use-lld }}

      - name: Build Rust
        run: make all
        working-directory: ./rust

      - name: Show Target Spec
        run: make show-target-info

      - name: Build Rust dist
        run: make dist
        working-directory: ./rust

      - name: Archive Rust dist
        uses: actions/upload-artifact@v4
        with:
          name: rust-${{ matrix.rust-targets }}_${{ matrix.xcode-version }}-${{ matrix.os }}
          path: ./rust/build/dist/*.xz

      - name: Archive target spec
        uses: actions/upload-artifact@v4
        with:
          name: rust-${{ matrix.rust-targets }}_${{ matrix.xcode-version }}-spec
          path: ./*.json
